### ISSUE TITLE
Retry Queries Option does not work

### ISSUE THREAD

**Issue by amedina33** [Pomax/node-flickrapi#29]
When retry_queries is true and the queryFlickr call fails due to no network or similar, then you get the following crash:
```
ReferenceError: queryFlickr is not defined
    at Request._callback (node_modules/flickrapi/src/utils.js:282:20)
    at self.callback (/node_modules/flickrapi/node_modules/request/index.js:148:22)
    at Request.emit (events.js:95:17)
    at ClientRequest.self.clientErrorHandler (/node_modules/flickrapi/node_modules/request/index.js:258:10)
    at ClientRequest.emit (events.js:95:17)
    at ClientRequest.onError (/node_modules/proxy-out/node_modules/tunnel/lib/tunnel.js:164:21)
    at ClientRequest.g (events.js:180:16)
    at ClientRequest.emit (events.js:95:17)
    at Socket.socketErrorListener (http.js:1547:9)
    at Socket.emit (events.js:95:17)
```

Added a quick fix to the utils.js:
            return  __this__.queryFlickr(queryArguments, flickrOptions, security, processResult, errors);
...
        processResult(false, body);
      }**.bind(this)**);

But should add some back off timer as well.

**Comment by Pomax** [comment]
... fixed in v0.3.32 >_>;
