### ISSUE TITLE
upload not work

### ISSUE THREAD

**Issue by askovpen** [Pomax/node-flickrapi#54]
```js
var Flickr = require("flickrapi"),                                                                                                     
    flickrOptions = {                                                                                                                  
    api_key: "xxx",                                                                                       
    secret: "xxx",                                                                                                        
    auth_token: 'xxx',                                                                                  
    nobrowser: true,                                                                                                                   
};                                                                                                                                     
var uploadOptions = {                                                                                                                  
    photos: [{                                                                                                                         
        title: 'test',                                                                                                                 
        photo: './file.jpg',                                                                                   
        is_public: 0,                                                                                                                  
        is_friend: 0,                                                                                                                  
        is_family: 0                                                                                                                   
    }]                                                                                                                                 
};                                                                                                                                     
Flickr.tokenOnly(flickrOptions, function(error, flickr) {                                                                              
    if (error) {                                                                                                                       
        throw error;                                                                                                                   
    }                                                                                                                                  
    Flickr.upload(uploadOptions, flickrOptions, function(err, result) {                                                                
        if(err) {                                                                                                                      
            throw err;                                                                                                               
        }                                                                                                                                      console.log("photos uploaded", result);                                                                                        
    });                                                                                                                                
});
```

```
TypeError: Cannot read property 'path' of undefined
    at FormData._multiPartHeader (/tmp/test/node_modules/flickrapi/node_modules/request/node_modules/form-data/lib/form_data.js:151:34)
    at FormData.append (/tmp/test/node_modules/flickrapi/node_modules/request/node_modules/form-data/lib/form_data.js:39:21)
    at /tmp/test/node_modules/flickrapi/src/utils.js:383:14
    at Array.forEach (native)
    at Object.module.exports.uploadtoFlickr (/tmp/test/node_modules/flickrapi/src/utils.js:382:33)
    at next (/tmp/test/node_modules/flickrapi/src/utils.js:341:14)
    at Object.module.exports.upload (/tmp/test/node_modules/flickrapi/src/utils.js:342:8)
    at /tmp/test/1.js:21:12
    at null._onTimeout (/tmp/test/node_modules/flickrapi/src/flickr-api-object.js:21:9)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
```

**Comment by Pomax** [comment]
does that file exist, relative to where the script is running?

**Comment by askovpen** [comment]
In perl version need only api_key,secret and auth_token for upload work: http://search.cpan.org/~cpb/Flickr-Upload/Upload.pm

**Comment by Pomax** [comment]
That might be, but that library and this JavaScript library are not relate, beyond the fact that both are implementations of wrappers around the Flickr API in their respective languages. If you have an oauth token and secret, use the `authenticate` function to ensure the API object gets authenticated. The `tokenOnly` access is for accessing the "plain API token only" public API (the same one you can use when you're not logged into Flickr online, like search images, or look at a user's public photos)
