### ISSUE TITLE
`body` sometimes undefined and flickrapi throws

### ISSUE THREAD

**Issue by neojski** [Pomax/node-flickrapi#64]
Sometimes the following happens:

```
/home/neo/repos/flickr-cli-uploadr/node_modules/flickrapi/src/utils.js:382
        if(body.indexOf('rsp stat="ok"')>-1) {
               ^
TypeError: Cannot read property 'indexOf' of undefined
    at Request._callback (/home/neo/repos/flickr-cli-uploadr/node_modules/flickrapi/src/utils.js:382:16)
    at self.callback (/home/neo/repos/flickr-cli-uploadr/node_modules/flickrapi/node_modules/request/index.js:148:22)
    at Request.emit (events.js:129:20)
    at ClientRequest.self.clientErrorHandler (/home/neo/repos/flickr-cli-uploadr/node_modules/flickrapi/node_modules/request/index.js:258:10)
    at ClientRequest.emit (events.js:107:17)
    at TLSSocket.socketOnEnd (_http_client.js:300:9)
    at TLSSocket.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```

There should be additional check for `error` in [`request.post` callback](https://github.com/Pomax/node-flickrapi/blob/3cd4508c41ca2c99131620e4baa8a92f9223bd2c/src/utils.js#L382).

**Comment by Pomax** [comment]
good find - I've left some comments on the PR you filed
