### ISSUE TITLE
Cannot find module './src/FlickrApi

### ISSUE THREAD

**Issue by mabahj** [Pomax/node-flickrapi#94]
It seems to me that tokentest.js (and test.js) calls './src/FlickrApi while the file actually is called FlickrAPI. This results in the following error on my Linux system:

    [zsh|shed|0.17]% node tokentest.js
    
    module.js:340
        throw err;
              ^
    Error: Cannot find module './src/FlickrApi'
        at Function.Module._resolveFilename (module.js:338:15)
        at Function.Module._load (module.js:280:25)
        at Module.require (module.js:364:17)
        at require (module.js:380:17)
        at Object.<anonymous> (/home/hjerto/node_modules/node-flickrapi-master_NEW/node-flickrapi-master/tokentest.js:3:14)
        at Module._compile (module.js:456:26)
        at Object.Module._extensions..js (module.js:474:10)
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:312:12)
        at Function.Module.runMain (module.js:497:10)

The error disappears if I change line 3 in tokentest.js from FlickrApi to FlickrAPI

**Comment by Pomax** [comment]
interesting case sensitivity. If you want to hit the edit button for https://github.com/Pomax/node-flickrapi/blob/master/tokentest.js and change that, then tell github to file a PR with that change, I'll merge it in.

**Comment by mabahj** [comment]
OK, that was two pull requests. My first ever. :)

**Comment by Pomax** [comment]
merged, and v0.5.1 published to npm =)
